Repository wanted-pre-onboarding-team-9/pre-onboarding-10th-1-9, pull requests merged in 2023-04, with the labels that each got.

#2 [FEATURE] PR, Issues 템플릿 추가
  .github/ISSUE_TEMPLATE/✨-feature-request.md
  .github/ISSUE_TEMPLATE/🐞-bug-report.md
  .github/pull_request_template.md
Labels: enhancement

#4 프로젝트 세팅
  .eslintrc.js
  .gitignore
  .husky/pre-commit
  .husky/pre-push
  .prettierrc.js
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/robots.txt
  src/@types/index.ts
  src/App.tsx
  src/api/index.ts
  src/components/index.ts
  src/hooks/index.ts
  src/index.css
  src/index.tsx
  src/pages/Main.tsx
  src/pages/NotFound.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/TodoList.tsx
  src/pages/index.ts
  src/react-app-env.d.ts
  src/routes/Auth.tsx
  src/routes/index.tsx
  src/utils/index.ts
  src/utils/storage.ts
  src/utils/token.ts
  tsconfig.json
Labels: enhancement

#11 프로젝트 세팅 관련 피드백 반영
  .eslintrc.js
  .prettierrc.js
  src/App.tsx
  src/api/index.ts
  src/pages/Main.tsx
  src/pages/NotFound.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/TodoList.tsx
  src/routes/Auth.tsx
  src/utils/index.ts
Labels: enhancement

#12 ✨ feat: 로그인/회원가입에 필요한 Custom hook과 검증 함수 추가
  src/hooks/index.ts
  src/hooks/useForm.tsx
  src/utils/validators.ts
Labels: enhancement

#13 ✨ feat: 로그인/회원가입 컴포넌트 생성 및 useForm 커스텀 훅과 연결
  src/components/form/EmailField.tsx
  src/components/form/ErrorMessage.tsx
  src/components/form/Form.tsx
  src/components/form/PasswordField.tsx
  src/components/form/style.tsx
  src/components/index.ts
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/style.tsx
Labels: enhancement

#17 :sparkles: feat: 메인 페이지에 로그인/회원가입 이동버튼 생성 및 적용
  src/pages/Main.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/style.tsx
Labels: enhancement

#14 TODO 페이지 기능 추가
  src/@types/index.ts
  src/@types/response.ts
  src/@types/todo.ts
  src/api/ApiUrl.ts
  src/api/todo.ts
  src/components/todo/Button.tsx
  src/components/todo/CheckBox.tsx
  src/components/todo/CreateTodo.tsx
  src/components/todo/SingleTodo.tsx
  src/components/todo/TextInput.tsx
  src/components/todo/style.tsx
  src/hooks/useInput.ts
  src/pages/TodoList.tsx
  src/routes/index.tsx
  src/routes/todoLoader.ts
Labels: enhancement

#15 ✨ feat: 로그인 / 회원가입 api 구현 및 연결
  src/@types/auth.ts
  src/@types/response.ts
  src/api/auth.ts
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/TodoList.tsx
  src/routes/todoLoader.ts
Labels: enhancement

#24 :bug: fix: token이 없는 상태로 /todo 방문 시 발생하는 401 에러 해결
  src/api/todo.ts
  src/pages/TodoList.tsx
  src/routes/index.tsx
  src/routes/todoLoader.ts
Labels: bug

#29 ✨ feat: 이메일/패스워드 필드에 입력값 없을 시 에러메시지 off
  src/hooks/useForm.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
Labels: enhancement

#30 ✨ feat: TODO 기능 개선
  src/@types/response.ts
  src/@types/todo.ts
  src/api/auth.ts
  src/api/todo.ts
  src/components/common/EmailField.tsx
  src/components/common/ErrorMessage.tsx
  src/components/common/Form.tsx
  src/components/common/PasswordField.tsx
  src/components/common/style.tsx
  src/components/todo/Button.tsx
  src/components/todo/CheckBox.tsx
  src/components/todo/CreateTodo.tsx
  src/components/todo/SingleTodo.tsx
  src/components/todo/TextInput.tsx
  src/components/todo/style.tsx
  src/hooks/useInput.ts
  src/pages/Main.tsx
  src/pages/NotFound.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/TodoList.tsx
  src/routes/index.tsx
Labels: enhancement

#31 💄 feat: favicon 수정
  .prettierrc.js
  public/favicon.ico
  public/index.html
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
Labels: enhancement

#33 :memo: docs: README 작성
  README.md
Labels: documentation

#34 :recycle: refactor: 에러 처리 코드 리팩토링
  src/@types/api.ts
  src/api/auth.ts
  src/api/index.ts
  src/api/todo.ts
  src/components/todo/CreateTodo.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
Labels: enhancement
